version: '2'
services:
  web:
    build: .
    ports:
      - "10616:10616"
    volumes:
      - .:/code
    environment:
      - HOST_IP=${HOST_IP}
      - SERVICE_NAME=LocationService
      - STAGE=${STAGE}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
